[dev]
   command = "yarn dev"
[build]
  command = "yarn generate"
  publish = "dist"
  functions = 'functions'  # directs netlify to where your functions directory is located

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
